AdminTask.createCluster('[-clusterConfig [-clusterName cluster-001 -preferLocal true]]')
AdminConfig.save()
AdminControl.invoke('WebSphere:name=DeploymentManager,process=dmgr,platform=common,node=localhostCellManager01,diagnosticProvider=true,version=9.0.5.18,type=DeploymentManager,mbeanIdentifier=DeploymentManager,cell=localhostCell01,spec=1.0', 'multiSync', '[false]', '[java.lang.Boolean]')
AdminConfig.save()
AdminTask.createClusterMember('[-clusterName cluster-001 -memberConfig [-memberNode localhostNode01 -memberName clusNode1-JVM-1 -memberWeight 2 -genUniquePorts true -replicatorEntry false] -firstMember [-templateName default -nodeGroup DefaultNodeGroup -coreGroup DefaultCoreGroup -resourcesScope cluster]]')
AdminConfig.save()
AdminTask.createClusterMember('[-clusterName cluster-001 -memberConfig [-memberNode localhostNode02 -memberName ClusNode2-JVM-1 -memberWeight 2 -genUniquePorts true -replicatorEntry false]]')
AdminConfig.save()
AdminConfig.reset()
AdminTask.createClusterMember('[-clusterName cluster-001 -memberConfig [-memberNode localhostNode01 -memberName clusNode1-JVM-2 -memberWeight 2 -genUniquePorts true -replicatorEntry false]]')
AdminConfig.save()
AdminTask.createClusterMember('[-clusterName cluster-001 -memberConfig [-memberNode localhostNode02 -memberName ClusNode2-JVM-2 -memberWeight 2 -genUniquePorts true -replicatorEntry false]]')
AdminConfig.save()
AdminConfig.reset()
AdminClusterManagement.startSingleCluster("cluster-001")
