AdminTask.createApplicationServer('localhostNode01', '[-name JVM-11 -templateName default -genUniquePorts true ]')
AdminConfig.save()
AdminTask.createApplicationServer('localhostNode02', '[-name JVM-21 -templateName default -genUniquePorts true ]')
AdminConfig.save()
AdminTask.createApplicationServer('localhostNode01', '[-name JVM-12 -templateName default -genUniquePorts true ]')
AdminConfig.save()
AdminTask.createApplicationServer('localhostNode02', '[-name JVM-22 -templateName default -genUniquePorts true ]')
AdminConfig.save()
AdminControl.invoke('WebSphere:name=DeploymentManager,process=dmgr,platform=common,node=localhostCellManager01,diagnosticProvider=true,version=9.0.5.18,type=DeploymentManager,mbeanIdentifier=DeploymentManager,cell=localhostCell01,spec=1.0', 'multiSync', '[false]', '[java.lang.Boolean]')
AdminConfig.reset()
